### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by sourabhxyz**

### CODE REVIEW

**Review by ajuggler — CHANGES_REQUESTED** [review]
Review fixed typo.  Added a minor change ("than" -> "then").

**Comment by sourabhxyz** [comment]
Sounds good @ajuggler, but now we are in bit of an issue as your approval would not help since you committed last.

**Review by ajuggler — APPROVED** [review]
Reviewed fixed typo.

**Review by ajuggler — APPROVED** [review]
Reviewed.

**Pull request merged**
